// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: messaging-service-api.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MessagingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   []string                   `protobuf:"bytes,1,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Template string                     `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Data     string                     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Override *MessagingRequest_Override `protobuf:"bytes,4,opt,name=override,proto3" json:"override,omitempty"`
}

func (x *MessagingRequest) Reset() {
	*x = MessagingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messaging_service_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagingRequest) ProtoMessage() {}

func (x *MessagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_service_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagingRequest.ProtoReflect.Descriptor instead.
func (*MessagingRequest) Descriptor() ([]byte, []int) {
	return file_messaging_service_api_proto_rawDescGZIP(), []int{0}
}

func (x *MessagingRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *MessagingRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *MessagingRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MessagingRequest) GetOverride() *MessagingRequest_Override {
	if x != nil {
		return x.Override
	}
	return nil
}

type MessagingRequest_Override struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverridePref bool   `protobuf:"varint,1,opt,name=override_pref,json=overridePref,proto3" json:"override_pref,omitempty"`
	Method       string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *MessagingRequest_Override) Reset() {
	*x = MessagingRequest_Override{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messaging_service_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagingRequest_Override) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagingRequest_Override) ProtoMessage() {}

func (x *MessagingRequest_Override) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_service_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagingRequest_Override.ProtoReflect.Descriptor instead.
func (*MessagingRequest_Override) Descriptor() ([]byte, []int) {
	return file_messaging_service_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MessagingRequest_Override) GetOverridePref() bool {
	if x != nil {
		return x.OverridePref
	}
	return false
}

func (x *MessagingRequest_Override) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

var File_messaging_service_api_proto protoreflect.FileDescriptor

var file_messaging_service_api_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x69,
	0x6e, 0x66, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x12, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01, 0x0a, 0x10, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x50, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72,
	0x69, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x69, 0x6e, 0x66, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52,
	0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x1a, 0x47, 0x0a, 0x08, 0x4f, 0x76, 0x65,
	0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6f, 0x76,
	0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x50, 0x72, 0x65, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x32, 0x91, 0x01, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x70, 0x69, 0x12, 0x2d, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x69,
	0x6e, 0x66, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4b, 0x0a, 0x0f, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x2e, 0x69,
	0x6e, 0x66, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x69, 0x6e, 0x66, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x05, 0x5a, 0x03, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messaging_service_api_proto_rawDescOnce sync.Once
	file_messaging_service_api_proto_rawDescData = file_messaging_service_api_proto_rawDesc
)

func file_messaging_service_api_proto_rawDescGZIP() []byte {
	file_messaging_service_api_proto_rawDescOnce.Do(func() {
		file_messaging_service_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_messaging_service_api_proto_rawDescData)
	})
	return file_messaging_service_api_proto_rawDescData
}

var file_messaging_service_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messaging_service_api_proto_goTypes = []interface{}{
	(*MessagingRequest)(nil),          // 0: inf.messaging_service_api.MessagingRequest
	(*MessagingRequest_Override)(nil), // 1: inf.messaging_service_api.MessagingRequest.Override
	(*empty.Empty)(nil),               // 2: google.protobuf.Empty
	(*Status)(nil),                    // 3: inf.Status
}
var file_messaging_service_api_proto_depIdxs = []int32{
	1, // 0: inf.messaging_service_api.MessagingRequest.override:type_name -> inf.messaging_service_api.MessagingRequest.Override
	2, // 1: inf.messaging_service_api.MessagingServiceApi.Status:input_type -> google.protobuf.Empty
	0, // 2: inf.messaging_service_api.MessagingServiceApi.InitiateMessage:input_type -> inf.messaging_service_api.MessagingRequest
	3, // 3: inf.messaging_service_api.MessagingServiceApi.Status:output_type -> inf.Status
	3, // 4: inf.messaging_service_api.MessagingServiceApi.InitiateMessage:output_type -> inf.Status
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messaging_service_api_proto_init() }
func file_messaging_service_api_proto_init() {
	if File_messaging_service_api_proto != nil {
		return
	}
	file_global_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messaging_service_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messaging_service_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagingRequest_Override); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messaging_service_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messaging_service_api_proto_goTypes,
		DependencyIndexes: file_messaging_service_api_proto_depIdxs,
		MessageInfos:      file_messaging_service_api_proto_msgTypes,
	}.Build()
	File_messaging_service_api_proto = out.File
	file_messaging_service_api_proto_rawDesc = nil
	file_messaging_service_api_proto_goTypes = nil
	file_messaging_service_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MessagingServiceApiClient is the client API for MessagingServiceApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagingServiceApiClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	InitiateMessage(ctx context.Context, in *MessagingRequest, opts ...grpc.CallOption) (*Status, error)
}

type messagingServiceApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagingServiceApiClient(cc grpc.ClientConnInterface) MessagingServiceApiClient {
	return &messagingServiceApiClient{cc}
}

func (c *messagingServiceApiClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inf.messaging_service_api.MessagingServiceApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceApiClient) InitiateMessage(ctx context.Context, in *MessagingRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/inf.messaging_service_api.MessagingServiceApi/InitiateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagingServiceApiServer is the server API for MessagingServiceApi service.
type MessagingServiceApiServer interface {
	Status(context.Context, *empty.Empty) (*Status, error)
	InitiateMessage(context.Context, *MessagingRequest) (*Status, error)
}

// UnimplementedMessagingServiceApiServer can be embedded to have forward compatible implementations.
type UnimplementedMessagingServiceApiServer struct {
}

func (*UnimplementedMessagingServiceApiServer) Status(context.Context, *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedMessagingServiceApiServer) InitiateMessage(context.Context, *MessagingRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateMessage not implemented")
}

func RegisterMessagingServiceApiServer(s *grpc.Server, srv MessagingServiceApiServer) {
	s.RegisterService(&_MessagingServiceApi_serviceDesc, srv)
}

func _MessagingServiceApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.messaging_service_api.MessagingServiceApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceApiServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingServiceApi_InitiateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceApiServer).InitiateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inf.messaging_service_api.MessagingServiceApi/InitiateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceApiServer).InitiateMessage(ctx, req.(*MessagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessagingServiceApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inf.messaging_service_api.MessagingServiceApi",
	HandlerType: (*MessagingServiceApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MessagingServiceApi_Status_Handler,
		},
		{
			MethodName: "InitiateMessage",
			Handler:    _MessagingServiceApi_InitiateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messaging-service-api.proto",
}
